version: '3.9'

services:

  db:
    image: mariadb
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
      MARIADB_USER: "${MARIADB_USER}"
      MARIADB_PASSWORD: "${MARIADB_PASSWORD}"
      MARIADB_DATABASE: "${MARIADB_DATABASE}"
    volumes:
      - db_data:/var/lib/mariadb
    networks:
      - mariadb_network

networks:
  mariadb_network:
    driver: bridge

volumes:
  db_data:
